schema: 1
extension: dispatch
config_key: extensions.relay
requires:
  - { extension: grove, via: grove_database }
  - { extension: grove_kv, via: grove_kv }
  - {extension: trove, via: artifacts.trove_store}
