package compose

import (
	"path/filepath"

	"github.com/xraph/forge/cmd/forge/internal/deploy/model"
	"github.com/xraph/forge/cmd/forge/internal/deploy/render"
	"gopkg.in/yaml.v3"
)

func (c *Compose) Relocate(d *model.Deployment, b *render.Bundle, dir string) (*render.Bundle, error) {
	destination, err := filepath.Abs(dir)
	if err != nil {
		return nil, err
	}

	var doc map[string]any
	if err := yaml.Unmarshal(b.Files["compose.yaml"].Content, &doc); err != nil {
		return nil, err
	}

	services, _ := doc["services"].(map[string]any)
	for _, svc := range d.Services {
		entry, _ := services[svc.Name].(map[string]any)

		build, ok := entry["build"].(map[string]any)
		if !ok {
			continue
		}

		contextRoot := c.root
		if d.Target.Build.Builder == "host" {
			contextRoot = filepath.Join(c.root, ".forge", "state", d.TargetName, d.Environment, "build", svc.Name)
		}

		relative, err := filepath.Rel(destination, contextRoot)
		if err != nil {
			return nil, err
		}

		build["context"] = filepath.ToSlash(relative)

		if d.Target.Build.Builder != "host" && svc.Image.Dockerfile == "" {
			file, err := filepath.Rel(c.root, filepath.Join(destination, svc.Name, "Dockerfile"))
			if err != nil {
				return nil, err
			}

			build["dockerfile"] = filepath.ToSlash(file)
		}
	}

	raw, err := yaml.Marshal(doc)
	if err != nil {
		return nil, err
	}

	relocated := render.New(d.TargetName, d.Environment)
	for _, file := range b.Sorted() {
		relocated.AddMode(file.Path, file.Content, file.Mode)
	}

	relocated.Add("compose.yaml", append([]byte("# Generated by forge deploy.\n"), raw...))

	return relocated, nil
}
