package dart

import (
	"strings"

	"github.com/xraph/forge/internal/client"
)

// renderLiveSocket renders lib/src/streaming/live_socket.dart, the machinery
// every streaming client shares: the connection state, reconnect with
// backoff, the connection timeout, the offline send queue, the heartbeat, the
// server's keepalive traffic, and the url and credentials a connect uses.
// Reconnection and credentials follow the generator config, as they do in the
// TypeScript clients.
func renderLiveSocket(config client.GeneratorConfig) string {
	reconnect := "false"
	if config.Features.Reconnection {
		reconnect = "true"
	}

	authParam, authField := "", ""
	headLine := "      final sent = headers;\n"
	tokenArg := ""

	if config.IncludeAuth {
		authParam = "    this.credentials,\n"
		authField = `
  /// Supplies credentials for each connect, as the REST client's are supplied.
  ///
  /// Their headers are sent where the platform can send headers. Where it
  /// cannot, as in a browser, a bearer token in them is sent as the token
  /// query parameter instead.
  final FutureOr<Map<String, String>> Function()? credentials;
`
		headLine = "      final sent = {...headers, ...?await options.credentials?.call()};\n      final token = web ? bearerToken(sent) : null;\n"
		tokenArg = "token: token, " //nolint:gosec // Dart source text, not a credential
	}

	return strings.NewReplacer(
		"{{RECONNECT}}", reconnect,
		"{{CREDENTIALS_PARAM}}", authParam,
		"{{CREDENTIALS_FIELD}}", authField,
		"{{OPEN_HEAD}}", headLine,
		"{{TOKEN_ARG}}", tokenArg,
	).Replace(liveSocketSource)
}

// liveSocketSource is the Dart source of live_socket.dart, with the parts the
// config decides as placeholders.
const liveSocketSource = `// Generated by forge. Do not edit.

import 'dart:async';
import 'dart:convert' show JsonUnsupportedObjectError;
import 'dart:math' as math;

import 'package:forge_client/forge_client.dart'
    show
        BackoffPolicy,
        StreamConnect,
        StreamConnectContext,
        StreamConnection,
        TransportUnavailable,
        forgeKeepalive,
        streamControlEvents;

const bool _web = bool.fromEnvironment('dart.library.js_interop');

/// Where a live socket is in its life.
enum LiveConnectionState {
  /// Not connected. It will try again when reconnecting is on and it was not
  /// closed on purpose.
  disconnected,

  /// Opening a connection.
  connecting,

  /// Open.
  connected,

  /// Waiting to try again after a drop.
  reconnecting,

  /// Closed, on purpose or after giving up.
  closed,

  /// The last attempt to open failed.
  error,
}

/// How a streaming client connects, reconnects and queues what it cannot send.
final class LiveOptions {
  /// Creates options; every value has the TypeScript clients' default.
  const LiveOptions({
    this.connectionTimeout = const Duration(milliseconds: 30000),
    this.reconnect = {{RECONNECT}},
    this.maxReconnectAttempts = 10,
    this.reconnectDelay = const Duration(milliseconds: 1000),
    this.maxReconnectDelay = const Duration(milliseconds: 30000),
    this.enableOfflineQueue = true,
    this.maxQueueSize = 1000,
    this.queueMessageTtl = const Duration(milliseconds: 300000),
{{CREDENTIALS_PARAM}}  });

  /// How long opening a connection may take.
  final Duration connectionTimeout;

  /// Whether to open another connection after a drop.
  final bool reconnect;

  /// Attempts in a row before giving up and closing.
  final int maxReconnectAttempts;

  /// The first wait before an attempt; each wait after doubles.
  final Duration reconnectDelay;

  /// The longest wait before an attempt.
  final Duration maxReconnectDelay;

  /// Whether a send while not connected waits for a connection.
  final bool enableOfflineQueue;

  /// The most sends that may wait.
  final int maxQueueSize;

  /// How long a send may wait before it fails.
  final Duration queueMessageTtl;
{{CREDENTIALS_FIELD}}}

/// The url a stream connects to: [path] under [base]'s own path, with [base]'s
/// query kept and [token] added to it as the token parameter. A socket's
/// scheme is the WebSocket form of [base]'s.
Uri streamUri(Uri base, String path, {String? token, bool socket = true}) {
  final root = base.path.endsWith('/') ? base.path.substring(0, base.path.length - 1) : base.path;
  final query = {
    ...base.queryParametersAll,
    if (token != null) 'token': [token],
  };
  final scheme = socket
      ? switch (base.scheme) {
          'https' => 'wss',
          'http' => 'ws',
          final other => other,
        }
      : base.scheme;
  return Uri(
    scheme: scheme,
    userInfo: base.userInfo,
    host: base.host,
    port: base.hasPort ? base.port : null,
    path: '$root$path',
    queryParameters: query.isEmpty ? null : query,
  );
}

/// The bearer token in [headers], if there is one.
String? bearerToken(Map<String, String> headers) {
  for (final entry in headers.entries) {
    if (entry.key.toLowerCase() != 'authorization') continue;
    final value = entry.value.trim();
    if (value.length > 7 && value.substring(0, 7).toLowerCase() == 'bearer ') {
      return value.substring(7).trim();
    }
  }
  return null;
}

/// Opens one connection; [attempt] counts the connections opened before it.
typedef LiveOpen = Future<StreamConnection> Function(int attempt);

/// Builds a [LiveOpen] for [path] under [baseUrl].
///
/// [web] chooses between sending credentials as headers and sending a bearer
/// token as a query parameter. It follows the platform and is a parameter only
/// so a test can try both.
LiveOpen liveOpen({
  required StreamConnect connect,
  required Uri baseUrl,
  required String path,
  required String endpoint,
  Map<String, String> headers = const {},
  LiveOptions options = const LiveOptions(),
  bool socket = true,
  bool web = _web,
}) => (attempt) async {
{{OPEN_HEAD}}  return connect(
    StreamConnectContext(
      url: streamUri(baseUrl, path, {{TOKEN_ARG}}socket: socket),
      endpoint: endpoint,
      headers: sent,
      attempt: attempt,
    ),
  );
};

Object? _ping() => const {'type': 'system', 'event': 'ping'};

final class _Timeout implements Exception {
  const _Timeout();
}

final class _Cancelled implements Exception {
  const _Cancelled();
}

final class _Queued {
  _Queued(this.frame, this.check) : queued = DateTime.now() {
    done.future.ignore();
  }

  final Object? Function() frame;
  final String? Function()? check;
  final DateTime queued;
  final done = Completer<void>();

}

/// A connection that opens itself, reopens after a drop, and holds on to what
/// it could not send.
///
/// Frames arrive on [frames], a broadcast stream that carries on across
/// reconnects, so any number of listeners can hear them and the socket answers
/// the server's pings whether or not anyone does.
final class LiveSocket {
  /// Creates a socket that opens with [open].
  ///
  /// With [heartbeat] the socket sends [heartbeatFrame] on that interval. With
  /// [keepalive] it answers the server's ping and keeps the ping and pong out
  /// of [frames]. With [events] it delivers only those events, as
  /// server-sent-event frames, and none of the control events. [onOpen] runs
  /// after each open and before the queue is sent, with whether the socket had
  /// been open before. [onLost] runs when the connection goes away.
  LiveSocket({
    required LiveOpen open,
    this.options = const LiveOptions(),
    this.heartbeat,
    this.heartbeatFrame = _ping,
    this.events,
    this.keepalive = false,
    this.onOpen,
    this.onLost,
  }) : _open = open,
       _backoff = BackoffPolicy(
         initial: options.reconnectDelay,
         max: options.maxReconnectDelay,
         attempts: options.maxReconnectAttempts,
       );

  /// How this socket connects, reconnects and queues.
  final LiveOptions options;

  /// How often to send [heartbeatFrame], or null for never.
  final Duration? heartbeat;

  /// The frame a heartbeat sends.
  final Object? Function() heartbeatFrame;

  /// The events to deliver, for a server-sent-event stream, or null for a socket.
  final Set<String>? events;

  /// Whether to answer the server's ping.
  final bool keepalive;

  /// Runs after each open, before the queue is sent.
  final Future<void> Function(bool reconnected)? onOpen;

  /// Runs when the connection goes away.
  final void Function()? onLost;

  final LiveOpen _open;
  final BackoffPolicy _backoff;
  final _random = math.Random();
  final _frames = StreamController<Object?>.broadcast();
  final _states = StreamController<LiveConnectionState>.broadcast();
  final _errors = StreamController<Object>.broadcast();
  final _queue = <_Queued>[];
  var _closed = Completer<void>();
  var _state = LiveConnectionState.disconnected;
  StreamConnection? _connection;
  StreamSubscription<Object?>? _subscription;
  Future<void>? _connecting;
  Timer? _beat;
  Timer? _retry;
  Timer? _openTimer;
  void Function()? _abandon;
  var _generation = 0;
  var _ready = false;
  var _wanted = true;
  var _disposed = false;
  var _everOpened = false;
  var _attempts = 0;
  var _opens = 0;

  /// The connection state.
  LiveConnectionState get state => _state;

  /// Changes of [state].
  Stream<LiveConnectionState> get states => _states.stream;

  /// What the server sends. It carries on across reconnects.
  Stream<Object?> get frames => _frames.stream;

  /// [frames], or any other stream of this socket, until [closed] completes.
  ///
  /// The stream may be listened to more than once. It ends when the current
  /// connection ends and nothing will reopen it, so an await-for over it
  /// finishes.
  Stream<T> until<T>(Stream<T> source) {
    late final StreamController<T> out;
    StreamSubscription<T>? subscription;
    out = StreamController<T>.broadcast(
      onListen: () {
        subscription = source.listen(out.add, onError: out.addError);
        unawaited(
          closed.then((_) {
            unawaited(subscription?.cancel());
            unawaited(out.close());
          }),
        );
      },
      onCancel: () => subscription?.cancel(),
    );
    return out.stream;
  }

  /// Failures that have no caller to take them: a frame that could not be
  /// read, a heartbeat that could not be sent, an [onOpen] that threw.
  Stream<Object> get errors => _errors.stream;

  /// The open connection, or null.
  StreamConnection? get connection => _connection;

  /// Completes when the current connection has ended and nothing will reopen
  /// it by itself: after a drop with reconnecting off, after giving up on
  /// reconnecting, and after [disconnect] or [dispose]. A later [connect]
  /// starts a new future.
  Future<void> get closed => _closed.future;

  /// How many sends are waiting.
  int get queueSize => _queue.length;

  /// Opens the connection. Calling it while open does nothing, and while
  /// opening waits for the same attempt. After [disconnect] it opens afresh,
  /// whatever attempt was under way. If [disconnect] or [dispose] cancels the
  /// attempt, this completes without an open connection.
  Future<void> connect() {
    if (_disposed) return Future.error(StateError('the client is closed'));
    if (_connection != null) return Future.value();
    final existing = _connecting;
    if (existing != null) return existing;
    final run = _connecting = _run();
    // Forget the attempt once it ends, however it ends. An attempt that fails
    // before its first await has ended before it is stored, so this cannot be
    // left to the attempt itself.
    unawaited(
      run.then<void>((_) {}, onError: (Object _) {}).whenComplete(() {
        if (identical(_connecting, run)) _connecting = null;
      }),
    );
    return run;
  }

  bool _current(int generation) => generation == _generation;

  Future<void> _run() async {
    final generation = _generation;
    _wanted = true;
    _retry?.cancel();
    _retry = null;
    if (_closed.isCompleted) _closed = Completer<void>();
    _setState(LiveConnectionState.connecting);
    final result = Completer<StreamConnection>();
    void abandon() {
      if (!result.isCompleted) result.completeError(const _Cancelled());
    }

    final timer = Timer(options.connectionTimeout, () {
      if (!result.isCompleted) result.completeError(const _Timeout());
    });
    _openTimer = timer;
    _abandon = abandon;
    final StreamConnection connection;
    try {
      final pending = _open(_opens++);
      unawaited(
        pending.then(
          (opened) {
            if (result.isCompleted) {
              unawaited(opened.close());
            } else {
              result.complete(opened);
            }
          },
          onError: (Object error, StackTrace stack) {
            if (!result.isCompleted) result.completeError(error, stack);
          },
        ),
      );
      connection = await result.future;
    } on _Cancelled {
      return;
    } on _Timeout {
      if (!_current(generation)) return;
      _failed(terminal: false);
      throw TimeoutException('Connection timeout', options.connectionTimeout);
    } on Object catch (error) {
      if (!_current(generation)) return;
      _failed(terminal: error is TransportUnavailable);
      rethrow;
    } finally {
      timer.cancel();
      if (identical(_openTimer, timer)) _openTimer = null;
      if (identical(_abandon, abandon)) _abandon = null;
    }
    if (!_current(generation) || _disposed) {
      await connection.close();
      return;
    }
    _connection = connection;
    _subscription = connection.messages.listen(
      (message) => _onMessage(connection, message),
      onError: (Object error, StackTrace stack) {
        if (!_frames.isClosed) _frames.addError(error, stack);
      },
    );
    unawaited(
      connection.closed.then((_) => _lost(connection), onError: (Object _) => _lost(connection)),
    );
    final reconnected = _everOpened;
    _everOpened = true;
    _attempts = 0;
    _ready = false;
    _setState(LiveConnectionState.connected);
    _startBeat(connection);
    try {
      await onOpen?.call(reconnected);
    } on Object catch (error) {
      _report(error);
    }
    if (!_current(generation) || !identical(_connection, connection)) return;
    _flush();
    _ready = true;
  }

  void _failed({required bool terminal}) {
    _setState(LiveConnectionState.error);
    if (terminal) {
      _end();
    } else {
      _scheduleReconnect();
    }
  }

  void _end() {
    if (!_closed.isCompleted) _closed.complete();
  }

  void _lost(StreamConnection lost) {
    if (!identical(_connection, lost)) return;
    _connection = null;
    // No newer attempt can exist while a connection is held, so this one, if it
    // is still setting up, is over; a retry must start its own.
    _connecting = null;
    _ready = false;
    _stopBeat();
    unawaited(_subscription?.cancel());
    _subscription = null;
    onLost?.call();
    if (!_wanted) {
      _setState(LiveConnectionState.closed);
      return;
    }
    _setState(LiveConnectionState.disconnected);
    _scheduleReconnect();
  }

  void _scheduleReconnect() {
    if (!options.reconnect || !_wanted || _disposed) {
      _end();
      return;
    }
    if (_attempts >= options.maxReconnectAttempts) {
      _wanted = false;
      _rejectQueue(StateError('Max reconnection attempts reached'));
      _setState(LiveConnectionState.closed);
      return;
    }
    _setState(LiveConnectionState.reconnecting);
    final wait = _backoff.delay(_attempts, _random.nextDouble());
    _attempts++;
    _retry = Timer(wait, () {
      _retry = null;
      unawaited(connect().then((_) {}, onError: (Object _) {}));
    });
  }

  void _onMessage(StreamConnection from, Object? message) {
    if (_frames.isClosed) return;
    final names = events;
    if (names != null) {
      if (message is! Map<Object?, Object?>) return;
      final name = message['event'];
      if (streamControlEvents.contains(name)) return;
      if (names.isNotEmpty && !names.contains(name)) return;
    } else if (keepalive &&
        message is Map<Object?, Object?> &&
        message['type'] == 'system' &&
        (message['event'] == 'ping' || message['event'] == 'pong')) {
      if (forgeKeepalive(message) case final reply?) {
        try {
          from.send(reply);
        } on Object catch (error) {
          _report(error);
        }
      }
      return;
    }
    _frames.add(message);
  }

  void _startBeat(StreamConnection connection) {
    final every = heartbeat;
    if (every == null) return;
    _beat = Timer.periodic(every, (_) {
      if (!identical(_connection, connection)) {
        _stopBeat();
        return;
      }
      try {
        connection.send(heartbeatFrame());
      } on Object catch (error) {
        _report(error);
        _stopBeat();
      }
    });
  }

  void _stopBeat() {
    _beat?.cancel();
    _beat = null;
  }

  void _report(Object error) {
    if (!_errors.isClosed) _errors.add(error);
  }

  void _setState(LiveConnectionState next) {
    if (_state == next) return;
    _state = next;
    if (!_states.isClosed) _states.add(next);
    if (next == LiveConnectionState.closed) _end();
  }

  /// Sends the frame [frame] builds, now if connected. Otherwise it waits in
  /// the queue until a connection is open, and fails if the queue is off or
  /// full, if it waits past its time, or if [check] names a reason it should
  /// not be sent after all.
  ///
  /// A send made while the connection is still being set up, or while earlier
  /// sends wait, joins the queue so it goes out after them.
  ///
  /// The frame is built when it is sent, so a timestamp or an encoding reflects
  /// that moment. The future completes once it is sent.
  Future<void> deliver(Object? Function() frame, {String? Function()? check}) {
    final open = _connection;
    if (open != null && ((_ready && _queue.isEmpty) || !options.enableOfflineQueue)) {
      try {
        open.send(frame());
        return Future.value();
      } on JsonUnsupportedObjectError catch (error) {
        // This message cannot be encoded; the connection is fine.
        return Future.error(error);
      } on Object catch (error) {
        // The transport failed, so the connection is no good: close it and let
        // the loss path reconnect.
        unawaited(open.close());
        return Future.error(error);
      }
    }
    if (!options.enableOfflineQueue) return Future.error(StateError('WebSocket is not connected'));
    if (_queue.length >= options.maxQueueSize) return Future.error(StateError('Message queue full'));
    final entry = _Queued(frame, check);
    _queue.add(entry);
    return entry.done.future;
  }

  void _flush() {
    final open = _connection;
    if (open == null) return;
    final now = DateTime.now();
    while (_queue.isNotEmpty) {
      final entry = _queue.first;
      if (now.difference(entry.queued) > options.queueMessageTtl) {
        _queue.removeAt(0);
        entry.done.completeError(StateError('Message expired in queue'));
        continue;
      }
      if (entry.check?.call() case final problem?) {
        _queue.removeAt(0);
        entry.done.completeError(StateError(problem));
        continue;
      }
      final Object? frame;
      try {
        frame = entry.frame();
      } on Object catch (error) {
        _queue.removeAt(0);
        entry.done.completeError(error);
        continue;
      }
      try {
        open.send(frame);
      } on JsonUnsupportedObjectError catch (error) {
        // This message cannot be encoded. It fails alone and the rest go on.
        _queue.removeAt(0);
        entry.done.completeError(error);
        continue;
      } on Object {
        // The transport failed. The entry stays at the head, and closing the
        // connection sends the socket through the loss path, which reconnects
        // and flushes again.
        unawaited(open.close());
        break;
      }
      _queue.removeAt(0);
      entry.done.complete();
    }
  }

  void _rejectQueue(Object error) {
    final waiting = [..._queue];
    _queue.clear();
    for (final entry in waiting) {
      entry.done.completeError(error);
    }
  }

  /// Drops what is waiting to be sent, failing it when [rejectPending] is true.
  void clearQueue({bool rejectPending = true}) {
    if (rejectPending) {
      _rejectQueue(StateError('Queue cleared'));
    } else {
      _queue.clear();
    }
  }

  /// Closes the connection and stops reconnecting, abandoning any attempt under
  /// way. What is waiting to be sent fails unless [rejectQueued] is false, in
  /// which case it stays for the next [connect]. The socket can be connected
  /// again.
  Future<void> disconnect({bool rejectQueued = true}) async {
    _generation++;
    _connecting = null;
    _wanted = false;
    _ready = false;
    _retry?.cancel();
    _retry = null;
    _openTimer?.cancel();
    _openTimer = null;
    _abandon?.call();
    _abandon = null;
    _stopBeat();
    if (rejectQueued) _rejectQueue(StateError('Connection closed'));
    final connection = _connection;
    final subscription = _subscription;
    _connection = null;
    _subscription = null;
    if (connection != null) onLost?.call();
    _setState(LiveConnectionState.closed);
    _end();
    await subscription?.cancel();
    await connection?.close();
  }

  /// Disconnects for good and closes every stream.
  Future<void> dispose({bool rejectQueued = true}) async {
    if (_disposed) return;
    await disconnect(rejectQueued: rejectQueued);
    _disposed = true;
    await _frames.close();
    await _states.close();
    await _errors.close();
  }
}
`
