package dart

import (
	"fmt"
	"sort"
	"strings"

	"github.com/xraph/forge/internal/client"
)

// Dependency constraints, from the contracts' version table.
const (
	sdkConstraint         = "^3.13.0"
	httpConstraint        = "^1.6.0"
	forgeClientConstraint = "^1.0.0-dev"
)

// renderPubspec renders pubspec.yaml. A package generated with hooks depends
// on forge_client; one without depends on package:http alone.
func renderPubspec(spec *client.APISpec, config client.GeneratorConfig) string {
	var b strings.Builder

	version := config.Version
	if version == "" {
		version = "1.0.0"
	}

	description := packageSummary(spec.Info.Description)
	if description == "" {
		description = "Generated Forge client for " + spec.Info.Title + "."
	}

	fmt.Fprintf(&b, "name: %s\n", config.PackageName)
	fmt.Fprintf(&b, "description: %s\n", yamlString(description))
	fmt.Fprintf(&b, "version: %s\n", version)
	b.WriteString("publish_to: none\n\n")
	b.WriteString("environment:\n")
	fmt.Fprintf(&b, "  sdk: %s\n\n", sdkConstraint)
	b.WriteString("dependencies:\n")

	if config.HooksEnabled() {
		fmt.Fprintf(&b, "  forge_client: %s\n", forgeClientConstraint)
	}

	fmt.Fprintf(&b, "  http: %s\n", httpConstraint)

	return b.String()
}

// packageSummary reduces a description to its first paragraph on one line.
func packageSummary(description string) string {
	paragraph, _, _ := strings.Cut(strings.TrimSpace(description), "\n\n")

	return strings.Join(strings.Fields(paragraph), " ")
}

// yamlString renders s as a double-quoted YAML scalar.
func yamlString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)

	return `"` + r.Replace(s) + `"`
}

// renderBarrel renders lib/<package>.dart, which exports every public file.
func renderBarrel(spec *client.APISpec, files map[string]string) string {
	var exports []string

	for name := range files {
		if !strings.HasPrefix(name, "lib/src/") || !strings.HasSuffix(name, ".dart") {
			continue
		}

		rel := strings.TrimPrefix(name, "lib/")

		switch {
		case strings.HasPrefix(rel, "src/codecs/"), rel == "src/support.dart", rel == "src/sync.dart":
			continue
		}

		exports = append(exports, fmt.Sprintf("export '%s';", rel))
	}

	exports = append(exports, "export 'src/support.dart' show Assign, Int64, Json, Unchanged, Value;")
	sort.Strings(exports)

	var b strings.Builder

	b.WriteString(generatedHeader)
	b.WriteString("\n")
	b.WriteString(docComment(packageSummary(spec.Info.Description), "Generated Forge client for "+spec.Info.Title+".", ""))
	b.WriteString("library;\n\n")
	b.WriteString(strings.Join(exports, "\n"))
	b.WriteString("\n")

	return b.String()
}

// renderReadme renders README.md, returned as the generated client's
// instructions so the output writer places it beside pubspec.yaml. Each
// optional section follows the file it describes, so the README never names
// something the run did not write.
func renderReadme(e *emission) string {
	var b strings.Builder

	spec, config, ops := e.spec, e.config, e.ops

	fmt.Fprintf(&b, "# %s\n\n", config.PackageName)

	if summary := packageSummary(spec.Info.Description); summary != "" {
		b.WriteString(summary + "\n\n")
	}

	fmt.Fprintf(&b, "Generated by `forge client generate --language dart` from %s %s. Do not edit it by hand: regenerate it.\n\n",
		spec.Info.Title, spec.Info.Version)

	b.WriteString("## Install\n\n```yaml\ndependencies:\n")
	fmt.Fprintf(&b, "  %s:\n    path: <path to this package>\n```\n\n", config.PackageName)

	b.WriteString("## Use the REST client\n\n```dart\n")
	fmt.Fprintf(&b, "import 'package:%s/%s.dart';\n\n", config.PackageName, config.PackageName)
	b.WriteString("final api = RestClient(baseUrl: Uri.parse('https://api.example.com'));\n")

	if len(ops) > 0 {
		fmt.Fprintf(&b, "// await api.%s(...);\n", e.paths[ops[0]])
	}

	b.WriteString("```\n\nA non-2xx response throws a subclass of the sealed `ApiError`, so a `switch` over it is exhaustive.\n")

	if e.hooks && len(ops) > 0 {
		writeBindingsSection(&b, e)
	}

	if len(e.paged) > 0 {
		b.WriteString("\n## Paginate\n\n")
		b.WriteString("A list operation that takes a cursor, page or offset has a stream that walks every page, fetching the next one as you read:\n\n```dart\n")
		fmt.Fprintf(&b, "await for (final item in api.%s(...)) {\n  // ...\n}\n```\n", e.paged[0].method)
		b.WriteString("\n`paginateAll` and `collectAll` in `lib/src/pagination.dart` do the same for a page function you write yourself.\n")
	}

	if _, ok := e.out.Files["lib/src/capabilities.dart"]; ok {
		b.WriteString("\n## Capabilities\n\n")
		b.WriteString("`lib/src/capabilities.dart` holds the scopes, roles and permissions the API declares, with `canCall`, `can`, `hasRole` and `hasPermission` over them. Hand `setPrincipal` what your sign-in gave you. ")
		b.WriteString("These answers are for deciding what to show. They are not access control: the client holds them and whoever runs it can change them, so the server has to authorize every request anyway.\n")
	}

	if len(e.streams) > 0 || hasFile(e.out.Files, "lib/src/streaming/streaming_client.dart") {
		writeStreamingSection(&b, e)
	}

	b.WriteString("\n## Integers\n\n")

	if config.Int64 == client.Int64Int {
		b.WriteString("Generated with `--int64=int`: int64 fields are Dart `int`s, which lose precision above 2^53 in a web build.\n")
	} else {
		b.WriteString("int64 fields are `Int64`, an extension type over the decimal string, so a web build keeps every digit. Regenerate with `--int64=int` for an app that never targets the web.\n")
	}

	return b.String()
}

// writeBindingsSection describes the hooks output: one binding per operation
// over package:forge_client.
func writeBindingsSection(b *strings.Builder, e *emission) {
	first := e.ops[0]

	b.WriteString("\n## Use the bindings\n\n")
	b.WriteString("Each operation is a binding over `package:forge_client`, usable from plain Dart, `forge_client_flutter` or `forge_client_riverpod`:\n\n```dart\n")
	b.WriteString("import 'package:forge_client/forge_client.dart';\n\n")
	b.WriteString("final cache = configureClient(\n  transport: RestTransport(baseUrl: Uri.parse('https://api.example.com')),\n  entities: entities,\n);\n")

	args := "const NoArgs()"
	if first.hasArgs() {
		args = first.args + "(...)"
	}

	fmt.Fprintf(b, "// final value = await %s(%s).fetch(cache);\n```\n", first.binding, args)
}

// writeStreamingSection lists the streaming clients the run wrote.
func writeStreamingSection(b *strings.Builder, e *emission) {
	b.WriteString("\n## Streaming\n\n")
	b.WriteString("Streaming clients live in `lib/src/streaming/` and connect through `package:forge_client`.\n")

	if len(e.streams) > 0 {
		classes := make([]string, len(e.streams))
		for i, sc := range e.streams {
			classes[i] = "`" + sc.class + "`"
		}

		fmt.Fprintf(b, "\nOne typed client per endpoint: %s.\n", strings.Join(classes, ", "))

		for _, sc := range e.streams {
			if !sc.ws {
				continue
			}

			fmt.Fprintf(b, "\n```dart\nfinal session = await %s(baseUrl: Uri.parse('https://api.example.com')).connect();\nsession.messages.listen(print);\n```\n", sc.class)

			break
		}
	}

	if hasFile(e.out.Files, "lib/src/streaming/streaming_client.dart") {
		b.WriteString("\n`StreamingClient` bundles the room, presence, typing and channel clients over one base URL.\n")
	}

	b.WriteString("\nA socket reconnects after a drop and queues what it could not send. `LiveOptions` sets how.\n")
}

func hasFile(files map[string]string, name string) bool {
	_, ok := files[name]

	return ok
}
