package dashboard

import (
	"github.com/xraph/forge/extensions/dashboard/contributor"
	"github.com/xraph/forgeui/bridge"
)

// DashboardAware is an optional interface that Forge extensions can implement
// to signal that they bundle a dashboard contributor. The dashboard extension
// auto-discovers extensions implementing this interface during Start() and
// registers their contributors automatically — no manual registration needed.
//
// The returned contributor can be an EmbeddedContributor (static build),
// SSRContributor (Node.js sidecar), or any other LocalContributor.
//
// Example implementation in an extension:
//
//	func (a *AuthExtension) DashboardContributor() contributor.LocalContributor {
//	    return newDashboardContributor() // generated by forge contributor build
//	}
type DashboardAware interface {
	DashboardContributor() contributor.LocalContributor
}

// BridgeAware is an optional interface that Forge extensions can implement
// to register custom Go↔JS bridge functions with the dashboard. Extensions
// implementing this interface have RegisterDashboardBridge called during
// dashboard Start() after the bridge is initialized.
//
// Example implementation:
//
//	func (a *AuthExtension) RegisterDashboardBridge(b *bridge.Bridge) error {
//	    return b.Register("auth.getStats", a.handleGetStats,
//	        bridge.WithDescription("Get auth statistics"),
//	    )
//	}
type BridgeAware interface {
	RegisterDashboardBridge(b *bridge.Bridge) error
}
