package dashboard

import (
	"github.com/xraph/forge/extensions/dashboard/contract"
	"github.com/xraph/forge/extensions/dashboard/contract/dispatcher"
	"github.com/xraph/forge/extensions/dashboard/contributor"
	"github.com/xraph/forge/extensions/dashboard/ui/shell"
	"github.com/xraph/forgeui/bridge"
)

// DashboardAware is an optional interface that Forge extensions can implement
// to signal that they bundle a dashboard contributor. The dashboard extension
// auto-discovers extensions implementing this interface during Start() and
// registers their contributors automatically — no manual registration needed.
//
// The returned contributor can be an EmbeddedContributor (static build),
// SSRContributor (Node.js sidecar), or any other LocalContributor.
//
// Example implementation in an extension:
//
//	func (a *AuthExtension) DashboardContributor() contributor.LocalContributor {
//	    return newDashboardContributor() // generated by forge contributor build
//	}
type DashboardAware interface {
	DashboardContributor() contributor.LocalContributor
}

// BridgeAware is an optional interface that Forge extensions can implement
// to register custom Go↔JS bridge functions with the dashboard. Extensions
// implementing this interface have RegisterDashboardBridge called during
// dashboard Start() after the bridge is initialized.
//
// Example implementation:
//
//	func (a *AuthExtension) RegisterDashboardBridge(b *bridge.Bridge) error {
//	    return b.Register("auth.getStats", a.handleGetStats,
//	        bridge.WithDescription("Get auth statistics"),
//	    )
//	}
type BridgeAware interface {
	RegisterDashboardBridge(b *bridge.Bridge) error
}

// DashboardAuthAware is an optional interface that Forge extensions can
// implement to provide authentication for the dashboard. The dashboard
// auto-discovers extensions implementing this interface during Start()
// and calls RegisterDashboardAuth with itself, allowing the extension
// to set up auth pages, auth checking, and tenant resolution.
//
// Example implementation:
//
//	func (a *AuthExtension) RegisterDashboardAuth(ext *dashboard.Extension) {
//	    ext.SetAuthPageProvider(myPageProvider)
//	    ext.SetAuthChecker(myAuthChecker)
//	    ext.EnableAuth()
//	}
type DashboardAuthAware interface {
	RegisterDashboardAuth(ext *Extension)
}

// DashboardFooterContributor is an optional interface that Forge extensions can
// implement to contribute custom actions to the sidebar footer user dropdown.
// The dashboard auto-discovers extensions implementing this interface during
// Start() and collects their actions for rendering in both the main dashboard
// sidebar and extension sidebars.
//
// Example implementation:
//
//	func (a *AuthExtension) DashboardUserDropdownActions(basePath string) []shell.UserDropdownAction {
//	    return []shell.UserDropdownAction{
//	        {Label: "Profile", Icon: "user", Href: basePath + "/ext/authsome/pages/profile"},
//	    }
//	}
type DashboardFooterContributor interface {
	DashboardUserDropdownActions(basePath string) []shell.UserDropdownAction
}

// ContractContributorAware is an optional interface that Forge extensions can
// implement to register a contract-based dashboard contributor (the slice (f)+
// shape — declarative YAML manifest + typed dispatcher handlers). The
// dashboard auto-discovers extensions implementing this interface during
// Start() and calls RegisterContractContributor with the dashboard's contract
// registry, warden registry, and dispatcher.
//
// Coexists with DashboardAware: an extension can implement both to register
// its legacy templ-based contributor AND its contract contributor during the
// migration window. New extensions should prefer this interface; legacy ones
// migrate over time per the per-slice (f, g, h) plan.
//
// Example implementation:
//
//	func (e *StreamingExtension) RegisterContractContributor(
//	    disp *dispatcher.Dispatcher,
//	    reg contract.Registry,
//	    wreg contract.WardenRegistry,
//	) error {
//	    return streamingcontract.Register(disp, reg, wreg, streamingcontract.Deps{
//	        Manager: func() streaming.Manager { return e.manager },
//	        Config:  func() streaming.Config { return e.config },
//	    })
//	}
type ContractContributorAware interface {
	RegisterContractContributor(
		disp *dispatcher.Dispatcher,
		reg contract.Registry,
		wreg contract.WardenRegistry,
	) error
}
