package images

import (
	"encoding/json"
	"errors"
	"github.com/xraph/forge/cmd/forge/internal/deploy/model"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

const BuildIgnore = ".git\n.forge\ndeployments\nnode_modules\n**/node_modules\n.env\n.env.*\n**/.env\n**/.env.*\n*.pem\n**/*.pem\nconfig*.yaml\nconfig*.yml\n**/config*.yaml\n**/config*.yml\n"

var goDirective = regexp.MustCompile(`(?m)^go (\d+\.\d+)`)

func Ignore(d *model.Deployment) []byte {
	var out strings.Builder
	out.WriteString(BuildIgnore)

	for _, path := range d.BuildExcludes {
		escaped := strings.NewReplacer("*", "\\*", "?", "\\?", "[", "\\[", "]", "\\]", "!", "\\!").Replace(filepath.ToSlash(path))
		out.WriteString(escaped + "\n")
	}

	return []byte(out.String())
}

func Dockerfile(d *model.Deployment, s model.Service, root string) ([]byte, error) {
	if d.Target.Build.Builder == "host" {
		return []byte("# Generated by forge deploy.\nFROM alpine:3.22\nRUN apk add --no-cache ca-certificates wget && adduser -D -u 65532 forge\nUSER forge\nWORKDIR /app\nCOPY app /app/app\nENTRYPOINT [\"/app/app\"]\n"), nil
	}

	if !filepath.IsLocal(s.MainPath) || strings.ContainsAny(s.MainPath, "\r\n") {
		return nil, errors.New("invalid main package path")
	}

	module := filepath.Join(root, s.MainPath)

	var raw []byte

	for {
		data, err := os.ReadFile(filepath.Join(module, "go.mod"))
		if err == nil {
			raw = data

			break
		}

		if module == root {
			return nil, errors.New("service has no go.mod inside the build context")
		}

		parent := filepath.Dir(module)
		if parent == module {
			return nil, errors.New("invalid module directory")
		}

		module = parent
	}

	version := "1.26"
	if m := goDirective.FindSubmatch(raw); m != nil {
		version = string(m[1])
	}

	if work, err := os.ReadFile(filepath.Join(root, "go.work")); err == nil {
		if match := goDirective.FindSubmatch(work); match != nil {
			candidate := string(match[1])
			if newerGo(candidate, version) {
				version = candidate
			}
		}
	}

	relative, err := filepath.Rel(root, module)
	if err != nil {
		return nil, err
	}

	main, err := filepath.Rel(module, filepath.Join(root, s.MainPath))
	if err != nil {
		return nil, err
	}

	args, err := json.Marshal([]string{"go", "build", "-mod=mod", "-trimpath", "-ldflags", "-s -w", "-o", "/out/app", "./" + filepath.ToSlash(main)})
	if err != nil {
		return nil, err
	}

	text := "# Generated by forge deploy.\nFROM golang:" + version + "-alpine AS build\nWORKDIR /src\nCOPY . .\nWORKDIR /src/" + filepath.ToSlash(relative) + "\nENV CGO_ENABLED=0\nRUN " + string(args) + "\n\nFROM alpine:3.22\nRUN apk add --no-cache ca-certificates wget && adduser -D -u 65532 forge\nUSER forge\nWORKDIR /app\nCOPY --from=build /out/app /app/app\nENTRYPOINT [\"/app/app\"]\n"

	return []byte(text), nil
}

func newerGo(candidate, current string) bool {
	a := strings.Split(candidate, ".")
	b := strings.Split(current, ".")

	for i := range 2 {
		x, _ := strconv.Atoi(a[i])

		y, _ := strconv.Atoi(b[i])
		if x != y {
			return x > y
		}
	}

	return false
}
