package shared

import (
	"context"
	"maps"
	"time"

	json "github.com/json-iterator/go"
)

// HealthManager defines the interface for health checking.
type HealthManager interface {
	// Name returns the name or identifier associated with the implementation.
	Name() string

	// Start initializes and starts the health manager, performing necessary setup like auto-registering checks and endpoints.
	Start(ctx context.Context) error

	// Stop gracefully stops the health manager and releases resources. It requires a context for controlled shutdown.
	Stop(ctx context.Context) error

	// OnHealthCheck performs health checks for the service and returns an error if any check fails.
	OnHealthCheck(ctx context.Context) error

	// Register registers a health check. Returns an error if the check name is already registered or invalid.
	Register(check HealthCheck) error

	// RegisterFn registers a function-based health check under a provided name. Returns an error if the name is already registered or invalid.
	RegisterFn(name string, check HealthCheckFn) error

	// Unregister removes a health check associated with the specified name. Returns an error if the operation fails.
	Unregister(name string) error

	// Check executes health checks for all registered services and returns a comprehensive health report.
	Check(ctx context.Context) *HealthReport

	// CheckOne initiates a health check for the specified check by name and returns its health result.
	CheckOne(ctx context.Context, name string) *HealthResult

	// GetStatus returns the current overall health status of the system or service.
	GetStatus() HealthStatus

	// Subscribe registers a callback function that triggers when health status changes.
	Subscribe(callback HealthCallback) error

	// GetLastReport retrieves the most recent health report generated by the health manager.
	GetLastReport() *HealthReport

	// GetChecks retrieves a map of all registered health checks with their corresponding names as keys.
	GetChecks() map[string]HealthCheck

	// GetStats retrieves statistics about the health checker, including registered checks, subscribers, uptime, and overall status.
	GetStats() *HealthCheckerStats

	// SetEnvironment sets the environment name for the health manager.
	SetEnvironment(name string)

	// SetVersion sets the version information for the health manager implementation.
	SetVersion(version string)

	// SetHostname sets the hostname for the health manager instance.
	SetHostname(hostname string)

	// Environment returns the name of the deployment environment as a string.
	Environment() string

	// Hostname returns the hostname of the system or service being monitored.
	Hostname() string

	// Version returns the version information of the health manager as a string.
	Version() string

	// StartTime returns the time when the health manager was initialized or started.
	StartTime() time.Time

	// Reload reloads the health configuration at runtime
	Reload(config *HealthConfig) error
}

// HealthCheckFn represents a single health check.
type HealthCheckFn func(ctx context.Context) *HealthResult

// HealthCheck defines the interface for health checks.
type HealthCheck interface {
	// Name returns the name of the health check implementation.
	Name() string

	// Check performs the health check and returns the result as a HealthResult.
	Check(ctx context.Context) *HealthResult

	// Timeout returns the maximum duration allowed for the health check to complete before timing out.
	Timeout() time.Duration

	// Critical returns true if the health check is considered critical, meaning its failure impacts the overall system health.
	Critical() bool

	// Dependencies returns a slice of strings representing the dependencies for the health check.
	Dependencies() []string
}

// HealthStatus represents the health status of a service or component.
type HealthStatus string

const (
	HealthStatusHealthy   HealthStatus = "healthy"
	HealthStatusDegraded  HealthStatus = "degraded"
	HealthStatusUnhealthy HealthStatus = "unhealthy"
	HealthStatusUnknown   HealthStatus = "unknown"
)

// String returns the string representation of the health status.
func (hs HealthStatus) String() string {
	return string(hs)
}

// IsHealthy returns true if the status is healthy.
func (hs HealthStatus) IsHealthy() bool {
	return hs == HealthStatusHealthy
}

// IsDegraded returns true if the status is degraded.
func (hs HealthStatus) IsDegraded() bool {
	return hs == HealthStatusDegraded
}

// IsUnhealthy returns true if the status is unhealthy.
func (hs HealthStatus) IsUnhealthy() bool {
	return hs == HealthStatusUnhealthy
}

// IsUnknown returns true if the status is unknown.
func (hs HealthStatus) IsUnknown() bool {
	return hs == HealthStatusUnknown
}

// Severity returns a numeric severity level for comparison.
func (hs HealthStatus) Severity() int {
	switch hs {
	case HealthStatusHealthy:
		return 0
	case HealthStatusDegraded:
		return 1
	case HealthStatusUnhealthy:
		return 2
	case HealthStatusUnknown:
		return 3
	default:
		return 3
	}
}

// HealthResult represents the result of a health check.
type HealthResult struct {
	Name      string            `json:"name"`
	Status    HealthStatus      `json:"status"`
	Message   string            `json:"message"`
	Details   map[string]any    `json:"details"`
	Timestamp time.Time         `json:"timestamp"`
	Duration  time.Duration     `json:"duration"`
	Error     string            `json:"error,omitempty"`
	Critical  bool              `json:"critical"`
	Tags      map[string]string `json:"tags,omitempty"`
}

// NewHealthResult creates a new health result.
func NewHealthResult(name string, status HealthStatus, message string) *HealthResult {
	return &HealthResult{
		Name:      name,
		Status:    status,
		Message:   message,
		Details:   make(map[string]any),
		Timestamp: time.Now(),
		Tags:      make(map[string]string),
	}
}

// WithDetails adds details to the health result.
func (hr *HealthResult) WithDetails(details map[string]any) *HealthResult {
	maps.Copy(hr.Details, details)

	return hr
}

// WithDetail adds a single detail to the health result.
func (hr *HealthResult) WithDetail(key string, value any) *HealthResult {
	hr.Details[key] = value

	return hr
}

// WithError adds an error to the health result.
func (hr *HealthResult) WithError(err error) *HealthResult {
	if err != nil {
		hr.Error = err.Error()
		if hr.Status == HealthStatusHealthy {
			hr.Status = HealthStatusUnhealthy
		}
	}

	return hr
}

// WithDuration sets the duration of the health check.
func (hr *HealthResult) WithDuration(duration time.Duration) *HealthResult {
	hr.Duration = duration

	return hr
}

// WithCritical marks the health check as critical.
func (hr *HealthResult) WithCritical(critical bool) *HealthResult {
	hr.Critical = critical

	return hr
}

func (hr *HealthResult) WithStatus(status HealthStatus) *HealthResult {
	hr.Status = status

	return hr
}

func (hr *HealthResult) WithMessage(message string) *HealthResult {
	hr.Message = message

	return hr
}

// WithTags adds tags to the health result.
func (hr *HealthResult) WithTags(tags map[string]string) *HealthResult {
	maps.Copy(hr.Tags, tags)

	return hr
}

// WithTag adds a single tag to the health result.
func (hr *HealthResult) WithTag(key, value string) *HealthResult {
	hr.Tags[key] = value

	return hr
}

func (hr *HealthResult) WithTimestamp(timestamp time.Time) *HealthResult {
	hr.Timestamp = timestamp

	return hr
}

func (hr *HealthResult) WithTimestampNow() *HealthResult {
	hr.Timestamp = time.Now()

	return hr
}

func (hr *HealthResult) String() string {
	return hr.Name + ": " + hr.Status.String() + " - " + hr.Message
}

// IsHealthy returns true if the health result is healthy.
func (hr *HealthResult) IsHealthy() bool {
	return hr.Status.IsHealthy()
}

// IsDegraded returns true if the health result is degraded.
func (hr *HealthResult) IsDegraded() bool {
	return hr.Status.IsDegraded()
}

// IsUnhealthy returns true if the health result is unhealthy.
func (hr *HealthResult) IsUnhealthy() bool {
	return hr.Status.IsUnhealthy()
}

// IsCritical returns true if the health check is critical.
func (hr *HealthResult) IsCritical() bool {
	return hr.Critical
}

// HealthReport represents a comprehensive health report.
type HealthReport struct {
	Overall     HealthStatus             `json:"overall"`
	Services    map[string]*HealthResult `json:"services"`
	Timestamp   time.Time                `json:"timestamp"`
	Duration    time.Duration            `json:"duration"`
	Version     string                   `json:"version"`
	Environment string                   `json:"environment"`
	Hostname    string                   `json:"hostname"`
	Uptime      time.Duration            `json:"uptime"`
	Metadata    map[string]any           `json:"metadata,omitempty"`
}

// NewHealthReport creates a new health report.
func NewHealthReport() *HealthReport {
	return &HealthReport{
		Overall:   HealthStatusUnknown,
		Services:  make(map[string]*HealthResult),
		Timestamp: time.Now(),
		Metadata:  make(map[string]any),
	}
}

// AddResult adds a health result to the report.
func (hr *HealthReport) AddResult(result *HealthResult) {
	hr.Services[result.Name] = result
}

// AddResults adds multiple health results to the report.
func (hr *HealthReport) AddResults(results []*HealthResult) {
	for _, result := range results {
		hr.AddResult(result)
	}
}

// WithVersion sets the version information.
func (hr *HealthReport) WithVersion(version string) *HealthReport {
	hr.Version = version

	return hr
}

// WithEnvironment sets the environment information.
func (hr *HealthReport) WithEnvironment(environment string) *HealthReport {
	hr.Environment = environment

	return hr
}

// WithHostname sets the hostname information.
func (hr *HealthReport) WithHostname(hostname string) *HealthReport {
	hr.Hostname = hostname

	return hr
}

// WithUptime sets the application uptime.
func (hr *HealthReport) WithUptime(uptime time.Duration) *HealthReport {
	hr.Uptime = uptime

	return hr
}

// WithDuration sets the duration of the health check.
func (hr *HealthReport) WithDuration(duration time.Duration) *HealthReport {
	hr.Duration = duration

	return hr
}

// WithMetadata adds metadata to the health report.
func (hr *HealthReport) WithMetadata(metadata map[string]any) *HealthReport {
	maps.Copy(hr.Metadata, metadata)

	return hr
}

// GetHealthyCount returns the number of healthy services.
func (hr *HealthReport) GetHealthyCount() int {
	count := 0

	for _, result := range hr.Services {
		if result.IsHealthy() {
			count++
		}
	}

	return count
}

// GetDegradedCount returns the number of degraded services.
func (hr *HealthReport) GetDegradedCount() int {
	count := 0

	for _, result := range hr.Services {
		if result.IsDegraded() {
			count++
		}
	}

	return count
}

// GetUnhealthyCount returns the number of unhealthy services.
func (hr *HealthReport) GetUnhealthyCount() int {
	count := 0

	for _, result := range hr.Services {
		if result.IsUnhealthy() {
			count++
		}
	}

	return count
}

// GetCriticalCount returns the number of critical services.
func (hr *HealthReport) GetCriticalCount() int {
	count := 0

	for _, result := range hr.Services {
		if result.IsCritical() {
			count++
		}
	}

	return count
}

// GetFailedCriticalCount returns the number of failed critical services.
func (hr *HealthReport) GetFailedCriticalCount() int {
	count := 0

	for _, result := range hr.Services {
		if result.IsCritical() && result.IsUnhealthy() {
			count++
		}
	}

	return count
}

// GetServicesByStatus returns services filtered by status.
func (hr *HealthReport) GetServicesByStatus(status HealthStatus) []*HealthResult {
	var results []*HealthResult

	for _, result := range hr.Services {
		if result.Status == status {
			results = append(results, result)
		}
	}

	return results
}

// GetCriticalServices returns all critical services.
func (hr *HealthReport) GetCriticalServices() []*HealthResult {
	var results []*HealthResult

	for _, result := range hr.Services {
		if result.IsCritical() {
			results = append(results, result)
		}
	}

	return results
}

// IsHealthy returns true if the overall health is healthy.
func (hr *HealthReport) IsHealthy() bool {
	return hr.Overall.IsHealthy()
}

// IsDegraded returns true if the overall health is degraded.
func (hr *HealthReport) IsDegraded() bool {
	return hr.Overall.IsDegraded()
}

// IsUnhealthy returns true if the overall health is unhealthy.
func (hr *HealthReport) IsUnhealthy() bool {
	return hr.Overall.IsUnhealthy()
}

// ToJSON converts the health report to JSON.
func (hr *HealthReport) ToJSON() ([]byte, error) {
	return json.MarshalIndent(hr, "", "  ")
}

// FromJSON creates a health report from JSON.
func FromJSON(data []byte) (*HealthReport, error) {
	var report HealthReport

	err := json.Unmarshal(data, &report)

	return &report, err
}

// Summary returns a summary of the health report.
func (hr *HealthReport) Summary() map[string]any {
	return map[string]any{
		"overall":         hr.Overall,
		"total_services":  len(hr.Services),
		"healthy_count":   hr.GetHealthyCount(),
		"degraded_count":  hr.GetDegradedCount(),
		"unhealthy_count": hr.GetUnhealthyCount(),
		"critical_count":  hr.GetCriticalCount(),
		"failed_critical": hr.GetFailedCriticalCount(),
		"timestamp":       hr.Timestamp,
		"duration":        hr.Duration,
		"version":         hr.Version,
		"environment":     hr.Environment,
		"hostname":        hr.Hostname,
		"uptime":          hr.Uptime,
	}
}

// HealthCallback is a callback function for health status changes.
type HealthCallback func(result *HealthResult)

// HealthReportCallback is a callback function for health report changes.
type HealthReportCallback func(report *HealthReport)

// HealthCheckerStats contains statistics about the health checker.
type HealthCheckerStats struct {
	RegisteredChecks int           `json:"registered_checks"`
	Subscribers      int           `json:"subscribers"`
	Started          bool          `json:"started"`
	Uptime           time.Duration `json:"uptime"`
	LastReportTime   time.Time     `json:"last_report_time"`
	OverallStatus    HealthStatus  `json:"overall_status"`
	LastReport       *HealthReport `json:"last_report,omitempty"`
}

// HealthConfig configures health checks.
type HealthConfig struct {
	Enabled                bool              `json:"enabled"                  yaml:"enabled"`
	CheckInterval          time.Duration     `json:"check_interval"           yaml:"check_interval"`
	ReportInterval         time.Duration     `json:"report_interval"          yaml:"report_interval"`
	EnableAutoDiscovery    bool              `json:"enable_auto_discovery"    yaml:"enable_auto_discovery"`
	EnablePersistence      bool              `json:"enable_persistence"       yaml:"enable_persistence"`
	EnableAlerting         bool              `json:"enable_alerting"          yaml:"enable_alerting"`
	MaxConcurrentChecks    int               `json:"max_concurrent_checks"    yaml:"max_concurrent_checks"`
	DefaultTimeout         time.Duration     `json:"default_timeout"          yaml:"default_timeout"`
	CriticalServices       []string          `json:"critical_services"        yaml:"critical_services"`
	DegradedThreshold      float64           `json:"degraded_threshold"       yaml:"degraded_threshold"`
	UnhealthyThreshold     float64           `json:"unhealthy_threshold"      yaml:"unhealthy_threshold"`
	EnableSmartAggregation bool              `json:"enable_smart_aggregation" yaml:"enable_smart_aggregation"`
	EnablePrediction       bool              `json:"enable_prediction"        yaml:"enable_prediction"`
	EnableEndpoints        bool              `json:"enable_endpoints"         yaml:"enable_endpoints"`
	EndpointPrefix         string            `json:"endpoint_prefix"          yaml:"endpoint_prefix"`
	HistorySize            int               `json:"history_size"             yaml:"history_size"`
	Tags                   map[string]string `json:"tags"                     yaml:"tags"`

	// Service specific configuration
	AutoRegister    bool `json:"auto_register"    yaml:"auto_register"`
	ExposeEndpoints bool `json:"expose_endpoints" yaml:"expose_endpoints"`
	EnableMetrics   bool `json:"enable_metrics"   yaml:"enable_metrics"`

	// Environment information
	Version     string `json:"version"     yaml:"version"`
	Environment string `json:"environment" yaml:"environment"`
}

// DefaultHealthConfig returns default health configuration.
func DefaultHealthConfig() HealthConfig {
	return HealthConfig{
		Enabled: true,
		// HealthPath:         "/_/health",
		// LivenessPath:       "/_/health/live",
		// ReadinessPath:      "/_/health/ready",
		// HealthCheckTimeout: 5 * time.Second,
	}
}
