package router

import "testing"

// forgeEnvelopePage is the shape the whole envelope path exists for: a
// paginated wrapper in which nothing is an entity.
//
// The declaration is empty, which is the ordinary case -- there is exactly one
// entity-typed property and naming it would be noise. The client generator
// resolves it and refuses rather than picks when a type has several.
//
// What this file asserts is only that the marker reaches the component schema.
// The client-side half -- that the marker then produces `entity: 'Order'`, a
// `rootType` of the wrapper, and the same tags a bare array provides -- is
// asserted end to end in
// internal/client/generators/typescript/e2e_envelope_test.go.
type forgeEnvelopePage struct {
	Items []forgeEnvelopeOrder `json:"items"`
	Total int                  `json:"total"`
}

func (forgeEnvelopePage) ForgeEnvelope() EnvelopeDef { return EnvelopeDef{} }

type forgeEnvelopeOrder struct {
	ID string `json:"id"`
}

func TestForgeEnvelopeMarksTheSchema(t *testing.T) {
	gen := newSchemaGenerator(make(map[string]*Schema), nil)

	schema, err := gen.GenerateSchema(forgeEnvelopePage{})
	if err != nil {
		t.Fatalf("GenerateSchema failed: %v", err)
	}

	// On the SCHEMA, not on a property: a page of orders is a page of orders
	// on every endpoint returning one, so the declaration travels with the type
	// rather than being repeated per route.
	if v, _ := schema.Extensions["x-forge-envelope"].(bool); !v {
		t.Fatalf("x-forge-envelope = %#v, want true (ForgeEnvelope was not honoured)",
			schema.Extensions["x-forge-envelope"])
	}
}

// forgeEnvelopeNamed names its property, the escape for a wrapper carrying more
// than one entity-typed field.
type forgeEnvelopeNamed struct {
	Orders    []forgeEnvelopeOrder `json:"orders"`
	Customers []forgeEnvelopeOrder `json:"customers"`
}

func (forgeEnvelopeNamed) ForgeEnvelope() EnvelopeDef {
	return EnvelopeDef{ItemsField: "orders"}
}

func TestForgeEnvelopeEmitsTheNamedProperty(t *testing.T) {
	gen := newSchemaGenerator(make(map[string]*Schema), nil)

	schema, err := gen.GenerateSchema(forgeEnvelopeNamed{})
	if err != nil {
		t.Fatalf("GenerateSchema failed: %v", err)
	}

	if got, _ := schema.Extensions["x-forge-envelope"].(string); got != "orders" {
		t.Fatalf("x-forge-envelope = %#v, want %q", schema.Extensions["x-forge-envelope"], "orders")
	}
}

// A pointer receiver, which is the shape most people write without thinking
// about it.
type forgeEnvelopePointerPage struct {
	Data []forgeEnvelopeOrder `json:"data"`
}

func (*forgeEnvelopePointerPage) ForgeEnvelope() EnvelopeDef { return EnvelopeDef{} }

func TestForgeEnvelopeHonoursPointerReceiver(t *testing.T) {
	gen := newSchemaGenerator(make(map[string]*Schema), nil)

	schema, err := gen.GenerateSchema(forgeEnvelopePointerPage{})
	if err != nil {
		t.Fatalf("GenerateSchema failed: %v", err)
	}

	if v, _ := schema.Extensions["x-forge-envelope"].(bool); !v {
		t.Fatalf("x-forge-envelope = %#v, want true for a pointer receiver",
			schema.Extensions["x-forge-envelope"])
	}
}

// ItemsField is the JSON property name, the same rule EntityDef.IDField
// follows. Naming a Go field instead is a declaration that would resolve to
// nothing, so it marks nothing rather than emitting a name the client
// generator will only warn about later.
type forgeEnvelopeGoFieldName struct {
	Items []forgeEnvelopeOrder `json:"items"`
}

func (forgeEnvelopeGoFieldName) ForgeEnvelope() EnvelopeDef {
	return EnvelopeDef{ItemsField: "Items"}
}

func TestForgeEnvelopeWithUnknownPropertyMarksNothing(t *testing.T) {
	gen := newSchemaGenerator(make(map[string]*Schema), nil)

	schema, err := gen.GenerateSchema(forgeEnvelopeGoFieldName{})
	if err != nil {
		t.Fatalf("GenerateSchema failed: %v", err)
	}

	if _, present := schema.Extensions["x-forge-envelope"]; present {
		t.Fatalf("x-forge-envelope = %#v, want nothing for a Go field name",
			schema.Extensions["x-forge-envelope"])
	}
}

// A type that does not implement the interface gets no extension at all, so a
// document generated by an application that never opts in is unchanged.
func TestWithoutForgeEnvelopeNothingIsMarked(t *testing.T) {
	gen := newSchemaGenerator(make(map[string]*Schema), nil)

	schema, err := gen.GenerateSchema(forgeEnvelopeOrder{})
	if err != nil {
		t.Fatalf("GenerateSchema failed: %v", err)
	}

	if _, present := schema.Extensions["x-forge-envelope"]; present {
		t.Fatalf("x-forge-envelope was set on a type that never declared it: %#v", schema.Extensions)
	}
}
