package codegen

import (
	"strings"
	"testing"

	"github.com/xraph/forge/extensions/dashboard/contributor/config"
)

func TestGenerateToString_StaticMode(t *testing.T) {
	cfg := &config.ContributorConfig{
		Name:        "auth",
		DisplayName: "Authentication",
		Version:     "1.0.0",
		Type:        "astro",
		Build: config.BuildConfig{
			Mode:        "static",
			UIDir:       "ui",
			DistDir:     "dist",
			EmbedPath:   "ui/dist",
			PagesDir:    "pages",
			WidgetsDir:  "widgets",
			SettingsDir: "settings",
			AssetsDir:   "assets",
		},
		Nav: []config.NavItemConfig{
			{Label: "Overview", Path: "/", Icon: "shield", Group: "Security", Priority: 0},
			{Label: "Sessions", Path: "/sessions", Icon: "clock", Group: "Security", Priority: 1},
		},
		Widgets: []config.WidgetConfig{
			{ID: "active-sessions", Title: "Active Sessions", Size: "sm", RefreshSec: 30},
		},
		Settings: []config.SettingConfig{
			{ID: "auth-config", Title: "Authentication Settings", Description: "Configure providers"},
		},
	}

	result, err := GenerateToString(cfg, "/workspace/extensions/auth")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Check that the generated code contains expected elements
	checks := []string{
		"// Code generated by forge contributor build. DO NOT EDIT.",
		"package auth",
		`"embed"`,
		`//go:embed ui/dist`,
		"var contributorDistFS embed.FS",
		`Name:        "auth"`,
		`DisplayName: "Authentication"`,
		`Version:     "1.0.0"`,
		`Label: "Overview"`,
		`Label: "Sessions"`,
		`ID: "active-sessions"`,
		`ID: "auth-config"`,
		"func newDashboardContributor() *contributor.EmbeddedContributor",
		`contributor.WithPagesDir("pages")`,
		`contributor.WithAssetsDir("assets")`,
	}

	for _, check := range checks {
		if !strings.Contains(result, check) {
			t.Errorf("generated code missing: %q\n\nGenerated:\n%s", check, result)
		}
	}
}

func TestGenerateToString_SSRMode(t *testing.T) {
	cfg := &config.ContributorConfig{
		Name:        "analytics",
		DisplayName: "Analytics",
		Version:     "2.0.0",
		Type:        "nextjs",
		Build: config.BuildConfig{
			Mode:     "ssr",
			UIDir:    "ui",
			DistDir:  ".next",
			SSREntry: "ui/.next/standalone/server.js",
		},
		Nav: []config.NavItemConfig{
			{Label: "Dashboard", Path: "/", Icon: "chart", Group: "Operations"},
		},
	}
	cfg.ApplyDefaults()

	result, err := GenerateToString(cfg, "/workspace/extensions/analytics")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	checks := []string{
		"package analytics",
		`Name:        "analytics"`,
		"func newDashboardContributor() *contributor.SSRContributor",
		"contributor.NewSSRContributor(",
		`"ui/.next/standalone/server.js"`,
		`contributor.WithSSRWorkDir("ui")`,
	}

	for _, check := range checks {
		if !strings.Contains(result, check) {
			t.Errorf("generated code missing: %q\n\nGenerated:\n%s", check, result)
		}
	}

	// Ensure no embed directive in SSR mode
	if strings.Contains(result, "//go:embed") {
		t.Error("SSR mode should not have //go:embed directive")
	}
}

func TestSanitizeVarPrefix(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"auth", "auth"},
		{"Auth", "auth"},
		{"my_ext", "myext"},
		{"", "contributor"},
	}

	for _, tt := range tests {
		result := sanitizeVarPrefix(tt.input)
		if result != tt.expected {
			t.Errorf("sanitizeVarPrefix(%q) = %q, want %q", tt.input, result, tt.expected)
		}
	}
}
