package codegen

// staticTemplate generates a Go file that embeds the static build output
// and creates an EmbeddedContributor. Framework-agnostic.
const staticTemplate = `// Code generated by forge contributor build. DO NOT EDIT.
// Source: forge.contributor.yaml — {{ .Name }} v{{ .Version }}

package {{ .Package }}

import (
	"embed"
	"io/fs"

	"github.com/xraph/forge/extensions/dashboard/contributor"
)

//go:embed {{ .EmbedPath }}
var contributorDistFS embed.FS

var {{ .VarPrefix }}ContributorManifest = &contributor.Manifest{
	Name:        "{{ .Name }}",
	DisplayName: "{{ .DisplayName }}",
	Version:     "{{ .Version }}",
{{- if .Icon }}
	Icon:        "{{ .Icon }}",
{{- end }}
	Nav: []contributor.NavItem{
{{- range .Nav }}
		{Label: "{{ .Label }}", Path: "{{ .Path }}", Icon: "{{ .Icon }}", Group: "{{ .Group }}", Priority: {{ .Priority }}},
{{- end }}
	},
	Widgets: []contributor.WidgetDescriptor{
{{- range .Widgets }}
		{ID: "{{ .ID }}", Title: "{{ .Title }}", Description: "{{ .Description }}", Size: "{{ .Size }}", RefreshSec: {{ .RefreshSec }}},
{{- end }}
	},
	Settings: []contributor.SettingsDescriptor{
{{- range .Settings }}
		{ID: "{{ .ID }}", Title: "{{ .Title }}", Description: "{{ .Description }}"},
{{- end }}
	},
}

// newDashboardContributor creates the embedded dashboard contributor backed
// by the static build output. Call this from DashboardContributor().
func newDashboardContributor() *contributor.EmbeddedContributor {
	sub, err := fs.Sub(contributorDistFS, "{{ .EmbedPath }}")
	if err != nil {
		panic("forge {{ .Name }} contributor: failed to sub FS: " + err.Error())
	}
	return contributor.NewEmbeddedContributor(
		{{ .VarPrefix }}ContributorManifest,
		sub,
		contributor.WithPagesDir("{{ .PagesDir }}"),
		contributor.WithWidgetsDir("{{ .WidgetsDir }}"),
		contributor.WithSettingsDir("{{ .SettingsDir }}"),
		contributor.WithAssetsDir("{{ .AssetsDir }}"),
	)
}
`

// ssrTemplate generates a Go file that creates an SSRContributor.
// No embed.FS needed — the Node.js process serves content at runtime.
const ssrTemplate = `// Code generated by forge contributor build. DO NOT EDIT.
// Source: forge.contributor.yaml — {{ .Name }} v{{ .Version }} (SSR)

package {{ .Package }}

import (
	"github.com/xraph/forge/extensions/dashboard/contributor"
)

var {{ .VarPrefix }}ContributorManifest = &contributor.Manifest{
	Name:        "{{ .Name }}",
	DisplayName: "{{ .DisplayName }}",
	Version:     "{{ .Version }}",
{{- if .Icon }}
	Icon:        "{{ .Icon }}",
{{- end }}
	Nav: []contributor.NavItem{
{{- range .Nav }}
		{Label: "{{ .Label }}", Path: "{{ .Path }}", Icon: "{{ .Icon }}", Group: "{{ .Group }}", Priority: {{ .Priority }}},
{{- end }}
	},
	Widgets: []contributor.WidgetDescriptor{
{{- range .Widgets }}
		{ID: "{{ .ID }}", Title: "{{ .Title }}", Description: "{{ .Description }}", Size: "{{ .Size }}", RefreshSec: {{ .RefreshSec }}},
{{- end }}
	},
	Settings: []contributor.SettingsDescriptor{
{{- range .Settings }}
		{ID: "{{ .ID }}", Title: "{{ .Title }}", Description: "{{ .Description }}"},
{{- end }}
	},
}

// newDashboardContributor creates the SSR dashboard contributor that runs
// a Node.js sidecar process. Call this from DashboardContributor().
func newDashboardContributor() *contributor.SSRContributor {
	return contributor.NewSSRContributor(
		{{ .VarPrefix }}ContributorManifest,
		"{{ .SSREntry }}",
		contributor.WithSSRWorkDir("{{ .WorkDir }}"),
	)
}
`
