id: nats-2
type: nats
version: "2"
image: nats:2-alpine
port: 4222
volume: /data
healthcheck: [wget, -qO-, "http://127.0.0.1:8222/healthz"]
dsn: "nats://{host}:{port}"
command: [-js, -sd, /data, -m, "8222"]
features: [jetstream]
